[config]
schemaVersion = "0.0.1"

[package]
namespace = "Ixrec"
name = "TeleportFromAnywhere"
versionNumber = "0.2.1"
description = "A Nine Sols mod that allows the player to use the Teleport menu from anywhere in the game, not just the Pavilion root node."
websiteUrl = "https://github.com/Ixrec/NineSolsTeleportFromAnywhere"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
